baseURL      = "https://cx48.github.io/NightFolio"
languageCode = "en-us"
title        = "NightFolio"
theme        = "NightFolio"
minVersion   = "0.115.0"

[params]
  description = "NightFolio is a lightweight Hugo theme designed for showcasing professional resumes and portfolios. It uses Tailwind CSS for styling and contains fully modular sections out of the box."

[outputs]
  home = ["HTML"]