name        = "NightFolio"
license     = "MIT"
licenseURL  = "https://github.com/cx48/NightFolio/blob/main/LICENSE"
min_version = "0.115.0"  
homepage    = "https://github.com/cx48/NightFolio"
repository  = "https://github.com/cx48/NightFolio"
demosite    = "https://cx48.github.io/NightFolio"
description = "NightFolio is a lightweight Hugo theme designed for showcasing professional resumes and portfolios. It uses Tailwind CSS for styling and contains fully modular sections out of the box."
tags        = ["resume", "tailwind", "responsive", "onepage"]
features    = ["assetsMinification", "markdownRendering"]

[author]
    name = "cx48"
    homepage = "https://github.com/cx48/"